#!/usr/bin/env bash

img_name=`docker images --filter=reference=sr-dev --format "{{.Repository}}"`
#img_name=`docker images --filter=reference=sr-dev`
if [[ -z "$img_name" ]]; then
    echo "Image sr-dev does not exist."
else
    echo "Image sr-dev exists."
    #docker images --filter=reference=sr-dev
fi

echo ""

inst=`docker ps -a --filter=name=sr-docker --format "{{.Status}}"`
if [[ -z "$inst" ]]; then
    echo "Container does not exist."
else
    # TODO: Check if the container is running or not
    echo "Container exists:"
    echo -n " -> "
    echo $inst
fi

echo ""
